spring.application.name=media
#to send mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kishorgowda435@gmail.com
spring.mail.password=kgqezbnpgxsvhamr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true